name: tbib_gen_timezone_serializable
description: This Package for support TZDateTime to Json serializable.
version: 0.0.1
homepage: "https://github.com/the-best-is-best/tbib_gen_timezone_serializable"

environment:
  sdk: ">=3.0.0 <4.0.0"
  # flutter: 3.0.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
