name: tbib_gen_timezone_serializable
description: This Package for support TZDateTime to Json serializable.
version: 1.0.1
homepage: "https://github.com/the-best-is-best/tbib_gen_timezone_serializable"

environment:
  sdk: ">=3.0.0 <4.0.0"
  # flutter: 3.0.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  timezone: ^0.10.0
  tbib_timezone_offset: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
